### ISSUE TITLE
about pitch_shift

### ISSUE THREAD

**Issue by zliangak** [jthickstun/pytorch_musicnet#1]
Hi, your works are very inspiring!

One thing confusing me is that, in musicnet.py line 122, why do you have to set "y[label.data[1]+shift] = 1"? Does it mean that the "note" is defined by the pitch, i.e., if there is a pitch shift, then the ground true note will change, too?

**Comment by jthickstun** [comment]
Hi Zhicong,

That's correct: applying a pitch-shift to audio changes the labels (notes) for that audio. For example, suppose we pitch-shift the audio up by one semitone: if the original audio was labeled with "B" and "F#" then the new audio should be labeled with "C" and "G".

This is a little different from the data augmentation tricks commonly used in vision. In vision, it's more common to use "label-preserving" transformations to distort images without actually changing the label on the image: for example, flips, rotations, and crops.

The "jitter" transformation for musicnet is more comparable vision's augmentation procedures: jitter detunes the audio slightly, without shifting it so far that the label changes.

Best,
John

**Comment by zliangak** [comment]
Great thanks!
