### ISSUE TITLE
Error when using the notebooks to download the dataset

### ISSUE THREAD

**Issue by hamzakeurti** [jthickstun/pytorch_musicnet#2]
I downloaded raw musicnet from this page:
https://homes.cs.washington.edu/~thickstn/start.html

I am using the notebooks' firts 3 cells to download the datasets, with mmap=False.
I was hoping I could downloadit this way before starting to use it formy project.

As I run the following line, with the root pointing to where the raw folder is:
`train_set = musicnet.MusicNet(root=root, train=True,download=True,mmap=False, window=window)`

The cell outputs:
Extracting musicnet.tar.gz
Processing...
Then a FileNotFoundError complaining about not finding "test_data"

I had already failed to download the dataset solely using the notebooks.

**Comment by jthickstun** [comment]
Hi Hamza--

Sorry about the hassle. The download script accidentally assumed the root directory was "./musicnet": I suspect you had set "root" to something different? You'll probably find "test_data" and the other extracted files in a "musicnet" directory that was created in the working directory where you ran your notebook.

I just pushed an update to the repo that should extract the data to the right root directory. I also pushed an update that streams the musicnet download and might fix the issue you saw with the download as well.

Let me know if these updates fix things on your end.

**Comment by hamzakeurti** [comment]
Hi John!

Thank you for replying so fast!
I got latest this morning, and tried to download solely through the notebook, it failed again but this time with a different error. The outputs after the first three cells were as follow:
Downloading https://homes.cs.washington.edu/~thickstn/media/musicnet.tar.gz
Extracting musicnet.tar.gz
Processing...
And then the following Error:
Error: iterator should return strings, not bytes (did you open the file in text mode?)

Thank you for spending of your time on this project.
I will try to find what's wrong too.

**Comment by jthickstun** [comment]
Are you using Python 3? I just pushed a commit that adds Python 3 support & I suspect it will solve this issue and some other other ones you might run into.

**Comment by hamzakeurti** [comment]
Indeed I use Python3, I forgot to mention that!
Your last commit fixed it!
So excited to start using this!
