### ISSUE TITLE
Accessing a specific audio with rec_ids

### ISSUE THREAD

**Issue by KinWaiCheuk** [jthickstun/pytorch_musicnet#3]
When I do  `train_set.rec_ids`, it gives me a list of song ids.

Then I try to access the audio by using `train_set.access(2560,0)`, it gives me the following error

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-23-4b0159987e34> in <module>
> ----> 1 train_set.access(2560,0)
> 
> /workspace/raven_data/AMT/MusicNet/pytorch_musicnet/musicnet.py in access(self, rec_id, s, shift, jitter)
>     106 
>     107         if self.mmap:
> --> 108             x = np.frombuffer(self.records[rec_id][0][s*sz_float:int(s+scale*self.window)*sz_float], dtype=np.float32).copy()
>     109         else:
>     110             fid,_ = self.records[rec_id]
> 
> KeyError: 2560

Then I tried 

```
with train_set, test_set:
    x, y = train_set.access(2560,0)
```
And the `x` and `y` are only empty arrays.

How to properly access the audio?

**Comment by jthickstun** [comment]
The beginning of the file is silent. Try a few seconds in:

```
fs = 44100 # 44100 samples per second
with train_set:
    x, y = train_set.access(2560,3*fs)

plt.plot(x)
print(np.nonzero(y))
```

**Comment by KinWaiCheuk** [comment]
So, the `.access` method can only access the audio for few seconds? Is there anyway to access the full audio and plot it out with the `train_set` ?

Also, why the code doesn't work without the `with train_set:` line? I am relatively new to Python, and I only used `with open(“filename”, “mode”) as f:` before. So, the `with train_set` is also a line that open the .npy files?

**Comment by jthickstun** [comment]
The access method is designed for retrieving mini-batches to train a transcription classifier. You could get the whole record and plot the first few seconds with something like this:

```
with train_set:
    x = np.frombuffer(train_set.records[2560][0][128:], dtype=np.float32).copy()
plt.plot(x[:5*44100])
```

You need to set `with train_set` to mmap the files. The `with` statement mmaps the files and then releases them afterwards. It's equivalent to writing this:

```
train_set.__enter__()
x = np.frombuffer(train_set.records[2560][0][128:], dtype=np.float32).copy()
train_set.__exit__()
plt.plot(x[:5*44100])
```
